[package]
name = "rust_shell"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shell"
path = "src/shell.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "linker=clang-12"]
[dependencies]
